CREATE DATABASE IF NOT EXISTS demo_shop_db;

USE demo_shop_db;

DROP TABLE IF EXISTS T_ACCOUNT;

CREATE TABLE `T_ACCOUNT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'user id',
  `BALANCE` BIGINT NOT NULL,
  PRIMARY KEY(`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;

DROP TABLE IF EXISTS T_GOODS;

CREATE TABLE `T_GOODS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `PRICE` BIGINT NOT NULL,
  `REMAINING` INT NOT NULL,
  PRIMARY KEY(`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;

DROP TABLE IF EXISTS T_PURCHASE;

CREATE TABLE `T_PURCHASE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` BIGINT NOT NULL,
  `GOODS_ID` BIGINT NOT NULL,
  `TOTAL_PRICE` BIGINT NOT NULL,
  `QUANTITY` INT NOT NULL,
  `PURCHASE_TYPE` CHAR(3) NOT NULL,
  `STATUS` CHAR(9) NOT NULL,
  PRIMARY KEY(`ID`),
  KEY(`ACCOUNT_ID`),
  KEY(`GOODS_ID`),
  KEY(`STATUS`),
  CONSTRAINT `PURCHASE_ACCOUNT_FK` FOREIGN KEY(`ACCOUNT_ID`) REFERENCES `T_ACCOUNT`(`ID`),
  CONSTRAINT `PURCHASE_GOODS_FK` FOREIGN KEY(`GOODS_ID`) REFERENCES `T_GOODS`(`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;
